### ISSUE TITLE
Cannot find ./paper

### ISSUE THREAD

**Issue by Mouah1er** [Protonull/PaperInstaller#2]
Hello, I am currently trying to use your tool because it is very useful, but when I try to run the `bash installer.bash` command, after your tool has cloned the paper repo, it sends me `-bash: ./paper: No such file or directory`, and there is nothing in the local maven repo. My version is 1.18.1. 
Thanks in advance!

**Comment by Protonull** [comment]
Should be fixed now. Please read the updated README for instructions on how to locally install Paper.
